-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."City"
(
    city_id integer NOT NULL DEFAULT nextval('cities_city_id_seq'::regclass),
    city_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cities_pkey PRIMARY KEY (city_id)
);

CREATE TABLE IF NOT EXISTS public."Course"
(
    course_id integer NOT NULL DEFAULT nextval('courses_course_id_seq'::regclass),
    course_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT courses_pkey PRIMARY KEY (course_id)
);

CREATE TABLE IF NOT EXISTS public."CourseTeacher"
(
    course_teacher_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    teacher_id integer NOT NULL,
    course_id integer NOT NULL DEFAULT 0,
    CONSTRAINT "CourseTeacher_pkey" PRIMARY KEY (course_teacher_id)
);

CREATE TABLE IF NOT EXISTS public."Enrollment"
(
    enrollment_id integer NOT NULL DEFAULT nextval('enrollments_enrollment_id_seq'::regclass),
    course_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT enrollments_pkey PRIMARY KEY (enrollment_id)
);

CREATE TABLE IF NOT EXISTS public."Group"
(
    group_id integer NOT NULL DEFAULT nextval('groups_group_id_seq'::regclass),
    group_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT groups_pkey PRIMARY KEY (group_id)
);

CREATE TABLE IF NOT EXISTS public."Holiday"
(
    holiday_id serial NOT NULL,
    holiday_date date NOT NULL,
    holiday_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Holiday_pkey" PRIMARY KEY (holiday_id)
);

CREATE TABLE IF NOT EXISTS public."Room"
(
    room_id integer NOT NULL DEFAULT nextval('rooms_room_id_seq'::regclass),
    room_number character varying(10) COLLATE pg_catalog."default" NOT NULL,
    capacity integer NOT NULL,
    CONSTRAINT rooms_pkey PRIMARY KEY (room_id)
);

CREATE TABLE IF NOT EXISTS public."Schedule"
(
    schedule_id integer NOT NULL DEFAULT nextval('schedule_schedule_id_seq'::regclass),
    room_id integer NOT NULL,
    "schedulе_date" date,
    time_table_id integer,
    enrollment_id integer,
    holiday_id integer DEFAULT 0,
    CONSTRAINT schedule_pkey PRIMARY KEY (schedule_id)
);

CREATE TABLE IF NOT EXISTS public."Student"
(
    student_id integer NOT NULL DEFAULT nextval('students_student_id_seq'::regclass),
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    middle_name character varying(50) COLLATE pg_catalog."default",
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    birth_date date,
    city_id integer,
    address text COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    phone bigint,
    parent_phone bigint,
    CONSTRAINT students_pkey PRIMARY KEY (student_id),
    CONSTRAINT students_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public."StudentGroup"
(
    student_group_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    student_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT "StudentGroup_pkey" PRIMARY KEY (student_group_id)
);

CREATE TABLE IF NOT EXISTS public."Teacher"
(
    teacher_id integer NOT NULL DEFAULT nextval('teachers_teacher_id_seq'::regclass),
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    middle_name character varying(50) COLLATE pg_catalog."default",
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    birth_date date,
    city_id integer,
    address text COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    phone bigint,
    CONSTRAINT teachers_pkey PRIMARY KEY (teacher_id),
    CONSTRAINT teachers_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public."TimeTable"
(
    time_table_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    lesson_number integer NOT NULL DEFAULT 1,
    schedule_type character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "TimeTable_pkey" PRIMARY KEY (time_table_id)
);

